<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1581149250441" stop="1581149250480">
  <name>test01</name>
  <labels/>
  <test-cases>
    <test-case start="1581149250441" status="passed" stop="1581149250444">
      <name>Test01.test01</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="8068-MainThread"/>
        <label name="host" value="Lily-PC"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1581149250445" status="failed" stop="1581149250480">
      <name>Test01.test02</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test01.Test01 object at 0x00000139CBA69080&gt;

    def test02(self):
&gt;       assert 0
E       assert 0

scripts\test01.py:7: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="8068-MainThread"/>
        <label name="host" value="Lily-PC"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
